### ISSUE TITLE
Feature request: cmd-enter or ctrl-enter to add tasks

### ISSUE THREAD

**Issue by dreeves** [alltom/todournament#1]
Workaround: Hit tab and then space to jump to the button and then hit it, which is almost as fast. Just that so many other websites support cmd-enter that that's what my fingers want to do.

Btw, Beeminder finally implemented cmd-enter to submit in 2021. ([UVI link](http://beeminder.com/changelog#3753))

PS: I guess it's ctrl-enter for windows and linux, cmd-enter for mac.

PPS: Todournament is so brilliant! Thank you for making it!

**Comment by alltom** [comment]
9d85ec43c1f17cfbbe978c00c481c0cd2b9fb8c5 should do it! I tested on macOS Safari, anyway. 😅

At any rate, let me know if this doesn't work, because it's a tiny change. You got my hopes up that I'd have a snippet to copy/paste at that UVI link, but the repo's private!

I think Beeminder might be the first community where this tool's gotten any traction. It's nice to finally find some people on my wavelength. :)

**Comment by dreeves** [comment]
Confirmed! Working for me. And get in touch about seeing the Beeminder repo! (We have a CLA etc.)
