### ISSUE TITLE
"I can't decide" button is a no-op

### ISSUE THREAD

**Issue by dreeves** [alltom/todournament#2]
This is on Chrome on macOS. Clicking the button seems to have no effect.

![image](https://user-images.githubusercontent.com/9928/188033872-1bffa02f-3450-4e37-b0cf-27d5baae228e.png)

**Comment by dreeves** [comment]
Oops, as soon as I submitted this, I tried it again and it worked! I now have no idea how to replicate this but intend to keep an eye out!

**Comment by alltom** [comment]
Sorry, I think it's just that it doesn't exclude the original pair of tasks when it picks two at random. I got used to hammering the button when there aren't many tasks left, but it'd be nice if pressing it always had an effect. It's just annoying to make that happen because of how that button is implemented. :\

**Comment by dreeves** [comment]
Ah, makes sense now! New idea: at least flip the order of the two tasks, left to right, if the same ones are chosen, just so it doesn't seem like the button has broken.

**Comment by ianmcb** [comment]
I just added a naive fix for this in my fork, and added an additional button to randomly decide the outcome of a comparison.

**Comment by dreeves** [comment]
Ooh, nice! Is that coming to the main app?

**Comment by alltom** [comment]
I'd merge it. :)
